#!groovy
// The above triggers groovy syntax highlighting in vim

buildscript {
	repositories {
		mavenCentral()
		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}
}

plugins {
    id "com.vanniktech.maven.publish" version "0.32.0"
}
apply plugin: "groovy"
apply plugin: "signing"

//Tmp commented due to:
//  No matching variant of org.apache.groovy:groovy:5.0.4 was found. The consumer was configured to
//      find a library for use during compile-time, compatible with Java 8, preferably not packaged as a jar,
//      preferably optimized for standard JVMs, and its dependencies declared externally...
//sourceCompatibility = 1.8
//targetCompatibility = 1.8

group = "org.liquibase"
archivesBaseName = "liquibase-groovy-dsl"
version = liquibaseGroovyDslVersion

repositories {
	mavenCentral()
	mavenLocal()
}


dependencies {
    if ("$groovyVersion".startsWith("3.")) {
        //1.x - 3.x groovy artifacts GAVs
        implementation "org.codehaus.groovy:groovy:${groovyVersion}"
        implementation "org.codehaus.groovy:groovy-sql:${groovyVersion}"
    } else {
        //4.x - now groovy artifacts GAVs
        implementation "org.apache.groovy:groovy:${groovyVersion}"
        implementation "org.apache.groovy:groovy-sql:${groovyVersion}"
    }

	// This seems redundant, but it isn't.  We need compileOnly so that the main classes will
    // compile, but that dependency doesn't transfer to the unit tests, so we also need
    // testCompile.
	compileOnly "org.liquibase:liquibase-core:${liquibaseVersion}"
	testImplementation "org.liquibase:liquibase-core:${liquibaseVersion}"
    testImplementation "junit:junit:${junitVersion}"
	testRuntimeOnly "com.h2database:h2:${h2Version}"
    testRuntimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"
}


task sourceJar(type: Jar) {
	description = "An archive of the source code for Maven Central"
    archiveClassifier = "sources"
	from sourceSets.main.allSource
}


task groovydocJar(type: Jar, dependsOn: groovydoc) {
	description = "An archive of the GroovyDocs for Maven Central"
    archiveClassifier = "javadoc"
	from groovydoc
}

// Configure the Vanniktech publishing plugin.
mavenPublishing {
    coordinates(group, archivesBaseName, liquibaseGroovyDslVersion)
    signAllPublications()
    // The vanniktech plugin is supposed to default to Maven Central, but as of 6/21/25, it still
    // defaults to the old OSSRH site.
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL)
    pom {
        name = "Liquibase Groovy DSL"
        description = "A Groovy-based DSL for the Liquibase database refactoring tool."
        url = "https://github.com/liquibase/liquibase-groovy-dsl"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "stevesaliman"
                name = "Steven C. Saliman"
                url = "https://github.com/stevesaliman/"
            }
        }
        scm {
            url = "https://github.com/liquibase/liquibase-groovy-dsl"
            connection = "scm:https://liquibase@github.com/liquibase/liquibase-groovy-dsl"
            developerConnection = "scm:git@github.com:liquibase/liquibase-groovy-dsl.git"
        }
    }
}

